In [1]:
import pyodbc
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
file_path = r"153 datasets/avall.mdb"
conn_str = r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=' + file_path + ';'

# 连接数据库
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

# 获取所有表名
table_names = [table.table_name for table in cursor.tables(tableType='TABLE')]
print("数据库中的表名：", table_names)

# 关闭连接
cursor.close()
conn.close()

数据库中的表名： ['aircraft', 'Country', 'ct_iaids', 'ct_seqevt', 'dt_aircraft', 'dt_events', 'dt_Flight_Crew', 'eADMSPUB_DataDictionary', 'engines', 'events', 'Events_Sequence', 'Findings', 'Flight_Crew', 'flight_time', 'injury', 'narratives', 'NTSB_Admin', 'Occurrences', 'seq_of_events', 'states']

In [3]:
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

# 获取所有表的名称
table_names = [table.table_name for table in cursor.tables(tableType='TABLE')]

# 打印每个表的字段信息
for table in table_names:
    columns = [column.column_name for column in cursor.columns(table=table)]
    print(f"\n表 '{table}' 的字段信息：", columns)

# 关闭连接
cursor.close()
conn.close()

表 'aircraft' 的字段信息： ['ev_id', 'Aircraft_Key', 'regis_no', 'ntsb_no', 'acft_missing', 'far_part', 'flt_plan_filed', 'flight_plan_activated', 'damage', 'acft_fire', 'acft_expl', 'acft_make', 'acft_model', 'acft_series', 'acft_serial_no', 'cert_max_gr_wt', 'acft_category', 'acft_reg_cls', 'homebuilt', 'fc_seats', 'cc_seats', 'pax_seats', 'total_seats', 'num_eng', 'fixed_retractable', 'type_last_insp', 'date_last_insp', 'afm_hrs_last_insp', 'afm_hrs', 'elt_install', 'elt_oper', 'elt_aided_loc_ev', 'elt_type', 'owner_acft', 'owner_street', 'owner_city', 'owner_state', 'owner_country', 'owner_zip', 'oper_individual_name', 'oper_name', 'oper_same', 'oper_dba', 'oper_addr_same', 'oper_street', 'oper_city', 'oper_state', 'oper_country', 'oper_zip', 'oper_code', 'certs_held', 'oprtng_cert', 'oper_cert', 'oper_cert_num', 'oper_sched', 'oper_dom_int', 'oper_pax_cargo', 'type_fly', 'second_pilot', 'dprt_pt_same_ev', 'dprt_apt_id', 'dprt_city', 'dprt_state', 'dprt_country', 'dprt_time', 'dprt_timezn', 'dest_same_local', 'dest_apt_id', 'dest_city', 'dest_state', 'dest_country', 'phase_flt_spec', 'report_to_icao', 'evacuation', 'lchg_date', 'lchg_userid', 'afm_hrs_since', 'rwy_num', 'rwy_len', 'rwy_width', 'site_seeing', 'air_medical', 'med_type_flight', 'acft_year', 'fuel_on_board', 'commercial_space_flight', 'unmanned', 'ifr_equipped_cert', 'elt_mounted_aircraft', 'elt_connected_antenna', 'elt_manufacturer', 'elt_model', 'elt_reason_other']

表 'Country' 的字段信息： ['COUNTRY_CODE', 'COUNTRY_NAME']

表 'ct_iaids' 的字段信息： ['ct_name', 'code_iaids', 'meaning', 'seq', 'ntsb_type', 'ntsb_code', 'avn_code', 'ntsb_codes_more', 'not_for_ntsb_use', 'eADMS_use', 'notes']

表 'ct_seqevt' 的字段信息： ['code', 'meaning']

表 'dt_aircraft' 的字段信息： ['ev_id', 'Aircraft_Key', 'col_name', 'code', 'lchg_date', 'lchg_userid']

表 'dt_events' 的字段信息： ['ev_id', 'col_name', 'code', 'lchg_date', 'lchg_userid']

表 'dt_Flight_Crew' 的字段信息： ['ev_id', 'Aircraft_Key', 'crew_no', 'col_name', 'code', 'lchg_date', 'lchg_userid']

表 'eADMSPUB_DataDictionary' 的字段信息： ['Category of Data', 'Table', 'Column', 'ct_name', 'code_iaids', 'meaning', 'Data Type eADMS', 'Length eADMS', 'short_desc', 'Question_Def', 'Code meaning', 'typeofchange', 'Change_notes']

表 'engines' 的字段信息： ['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type', 'eng_mfgr', 'eng_model', 'power_units', 'hp_or_lbs', 'lchg_userid', 'lchg_date', 'carb_fuel_injection', 'propeller_type', 'propeller_make', 'propeller_model', 'eng_time_total', 'eng_time_last_insp', 'eng_time_overhaul']

表 'events' 的字段信息： ['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'ev_dow', 'ev_time', 'ev_tmzn', 'ev_city', 'ev_state', 'ev_country', 'ev_site_zipcode', 'ev_year', 'ev_month', 'mid_air', 'on_ground_collision', 'latitude', 'longitude', 'latlong_acq', 'apt_name', 'ev_nr_apt_id', 'ev_nr_apt_loc', 'apt_dist', 'apt_dir', 'apt_elev', 'wx_brief_comp', 'wx_src_iic', 'wx_obs_time', 'wx_obs_dir', 'wx_obs_fac_id', 'wx_obs_elev', 'wx_obs_dist', 'wx_obs_tmzn', 'light_cond', 'sky_cond_nonceil', 'sky_nonceil_ht', 'sky_ceil_ht', 'sky_cond_ceil', 'vis_rvr', 'vis_rvv', 'vis_sm', 'wx_temp', 'wx_dew_pt', 'wind_dir_deg', 'wind_dir_ind', 'wind_vel_kts', 'wind_vel_ind', 'gust_ind', 'gust_kts', 'altimeter', 'wx_dens_alt', 'wx_int_precip', 'metar', 'ev_highest_injury', 'inj_f_grnd', 'inj_m_grnd', 'inj_s_grnd', 'inj_tot_f', 'inj_tot_m', 'inj_tot_n', 'inj_tot_s', 'inj_tot_t', 'invest_agy', 'ntsb_docket', 'ntsb_notf_from', 'ntsb_notf_date', 'ntsb_notf_tm', 'fiche_number', 'lchg_date', 'lchg_userid', 'wx_cond_basic', 'faa_dist_office', 'dec_latitude', 'dec_longitude']

表 'Events_Sequence' 的字段信息： ['ev_id', 'Aircraft_Key', 'Occurrence_No', 'Occurrence_Code', 'Occurrence_Description', 'phase_no', 'eventsoe_no', 'Defining_ev', 'lchg_date', 'lchg_userid']

表 'Findings' 的字段信息： ['ev_id', 'Aircraft_Key', 'finding_no', 'finding_code', 'finding_description', 'category_no', 'subcategory_no', 'section_no', 'subsection_no', 'modifier_no', 'Cause_Factor', 'lchg_date', 'lchg_userid', 'cm_inPc']

表 'Flight_Crew' 的字段信息： ['ev_id', 'Aircraft_Key', 'crew_no', 'crew_category', 'crew_age', 'crew_sex', 'crew_city', 'crew_res_state', 'crew_res_country', 'med_certf', 'med_crtf_vldty', 'date_lst_med', 'crew_rat_endorse', 'crew_inj_level', 'seatbelts_used', 'shldr_harn_used', 'crew_tox_perf', 'seat_occ_pic', 'pc_profession', 'bfr', 'bfr_date', 'ft_as_of', 'lchg_date', 'lchg_userid', 'seat_occ_row', 'infl_rest_inst', 'infl_rest_depl', 'child_restraint', 'med_crtf_limit', 'mr_faa_med_certf', 'pilot_flying', 'available_restraint', 'restraint_used']

表 'flight_time' 的字段信息： ['ev_id', 'Aircraft_Key', 'crew_no', 'flight_type', 'flight_craft', 'flight_hours', 'lchg_date', 'lchg_userid']

表 'injury' 的字段信息： ['ev_id', 'Aircraft_Key', 'inj_person_category', 'injury_level', 'inj_person_count', 'lchg_date', 'lchg_userid']

表 'narratives' 的字段信息： ['ev_id', 'Aircraft_Key', 'narr_accp', 'narr_accf', 'narr_cause', 'narr_inc', 'lchg_date', 'lchg_userid']

表 'NTSB_Admin' 的字段信息： ['ev_id', 'rec_stat', 'approval_date', 'lchg_userid', 'lchg_date']

表 'Occurrences' 的字段信息： ['ev_id', 'Aircraft_Key', 'Occurrence_No', 'Occurrence_Code', 'Phase_of_Flight', 'Altitude', 'lchg_date', 'lchg_userid']

表 'seq_of_events' 的字段信息： ['ev_id', 'Aircraft_Key', 'Occurrence_No', 'seq_event_no', 'group_code', 'Subj_Code', 'Cause_Factor', 'Modifier_Code', 'Person_Code', 'lchg_date', 'lchg_userid']

表 'states' 的字段信息： ['state', 'name', 'faa_region']

In [4]:
# 连接数据库
conn = pyodbc.connect(conn_str)

# 替换为你想查看的表名
table_name = "events"  

# 使用 pandas 读取表的数据
query = f"SELECT * FROM {table_name}"  # 读取前 5 行数据
df = pd.read_sql(query, conn)

print(f"表 '{table_name}' 的行数：\n", len(df))
print(f"表 '{table_name}' 概览：\n", df)

# 关闭连接
conn.close()

表 'events' 的行数：
 28119
表 'events' 概览：
                 ev_id     ntsb_no ev_type    ev_date ev_dow  ev_time ev_tmzn  \
0      20080211X00175  DFW08RA039     ACC 2008-01-10     Th   1907.0     UTC
1      20080107X00026  SEA08LA057     ACC 2008-01-01     Tu   2230.0     UTC
2      20080109X00036  DFW08CA054     ACC 2008-01-01     Tu   2200.0     UTC
3      20080107X00027  DFW08LA055     ACC 2008-01-03     Th    825.0     UTC
4      20080115X00051  DEN08CA047     ACC 2008-01-02     We   2230.0     UTC
...               ...         ...     ...        ...    ...      ...     ...
28114  20241029195408  WPR25LA028     ACC 2024-10-25     Fr   1956.0     UTC
28115  20241029195410  ERA25LA030     ACC 2024-10-17     Th   1915.0     UTC
28116  20241030195412  DCA25LA015     ACC 2024-10-29     Tu      NaN    None
28117  20241030195414  DCA25WA016     INC 2024-10-21     Mo    452.0     UTC
28118  20241030195417  WPR25LA029     ACC 2024-10-29     Tu   2245.0     UTC

             ev_city ev_state ev_country  ... ntsb_notf_from  ntsb_notf_date  \
0       Pitt Meadows     None         CA  ...           None            None
1             Sonoma       CA        USA  ...           None            None
2             Arcola       TX        USA  ...           None            None
3      Oklahoma City       OK        USA  ...           None            None
4           Loveland       CO        USA  ...           None            None
...              ...      ...        ...  ...            ...             ...
28114       Palmdale       CA        USA  ...           None            None
28115    Martinsburg       PA        USA  ...           None            None
28116     Louisville       KY        USA  ...           None            None
28117     Guangzhou        OF         CH  ...           None            None
28118       Pinedale       WY        USA  ...           None            None

       ntsb_notf_tm fiche_number           lchg_date lchg_userid  \
0              None         None 2023-08-03 13:29:08      gibs-i
1              None         None 2020-09-25 18:05:31        None
2              None         None 2020-09-25 18:05:31        None
3              None         None 2020-09-25 18:04:02        None
4              None         None 2020-09-25 18:06:16        None
...             ...          ...                 ...         ...
28114          None         None 2024-10-29 22:09:28        basp
28115          None         None 2024-10-31 15:22:28       mccl3
28116          None         None 2024-10-30 15:29:32       sils1
28117          None         None 2024-10-30 15:42:05       sils1
28118          None         None 2024-10-30 20:32:09        basp

      wx_cond_basic faa_dist_office dec_latitude dec_longitude
0              None            None    49.216634   -122.683870
1               VMC            None    38.223888   -122.449722
2               VMC            None    29.506111    -95.476669
3               VMC            None    35.533611    -97.641387
4               VMC            None    40.451667   -105.001113
...             ...             ...          ...           ...
28114          None            None          NaN           NaN
28115           VMC            None          NaN           NaN
28116          None            None          NaN           NaN
28117          None            None          NaN           NaN
28118           VMC            None          NaN           NaN

[28119 rows x 73 columns]

In [5]:
# 连接数据库
conn = pyodbc.connect(conn_str)

# 查询 on_ground_collision 列中各唯一值的条数
query = """
SELECT on_ground_collision, COUNT(*) as count
FROM events
GROUP BY on_ground_collision
"""
df = pd.read_sql(query, conn)

print("on_ground_collision 列中各唯一值的条数：\n", df)

# 关闭连接
conn.close()

on_ground_collision 列中各唯一值的条数：
   on_ground_collision  count
0                None  27684
1                   N    175
2                   Y    260

In [12]:
# 连接数据库
conn = pyodbc.connect(conn_str)

# 查询 on_ground_collision 列中值为 Y 的行
query = "SELECT * FROM events WHERE on_ground_collision = 'Y' OR on_ground_collision IS NULL"
df = pd.read_sql(query, conn)

print("collision number  = ", len(df))  
print("events 表中 on_ground_collision 列值不为 N 的行：\n", df)  # 显示前几行数据
import pandas as pd

# save
df.to_excel('collisions.xlsx', index=False)

# 关闭连接
conn.close()

collision number  =  27944
events 表中 on_ground_collision 列值不为 N 的行：
                 ev_id     ntsb_no ev_type    ev_date ev_dow  ev_time ev_tmzn  \
0      20080211X00175  DFW08RA039     ACC 2008-01-10     Th   1907.0     UTC
1      20080109X00036  DFW08CA054     ACC 2008-01-01     Tu   2200.0     UTC
2      20080107X00027  DFW08LA055     ACC 2008-01-03     Th    825.0     UTC
3      20080115X00051  DEN08CA047     ACC 2008-01-02     We   2230.0     UTC
4      20080115X00047  MIA08LA035     ACC 2008-01-05     Sa   2045.0     UTC
...               ...         ...     ...        ...    ...      ...     ...
27939  20241029195408  WPR25LA028     ACC 2024-10-25     Fr   1956.0     UTC
27940  20241029195410  ERA25LA030     ACC 2024-10-17     Th   1915.0     UTC
27941  20241030195412  DCA25LA015     ACC 2024-10-29     Tu      NaN    None
27942  20241030195414  DCA25WA016     INC 2024-10-21     Mo    452.0     UTC
27943  20241030195417  WPR25LA029     ACC 2024-10-29     Tu   2245.0     UTC

             ev_city ev_state ev_country  ... ntsb_notf_from  ntsb_notf_date  \
0       Pitt Meadows     None         CA  ...           None            None
1             Arcola       TX        USA  ...           None            None
2      Oklahoma City       OK        USA  ...           None            None
3           Loveland       CO        USA  ...           None            None
4       Spotsylvania       VA        USA  ...           None            None
...              ...      ...        ...  ...            ...             ...
27939       Palmdale       CA        USA  ...           None            None
27940    Martinsburg       PA        USA  ...           None            None
27941     Louisville       KY        USA  ...           None            None
27942     Guangzhou        OF         CH  ...           None            None
27943       Pinedale       WY        USA  ...           None            None

       ntsb_notf_tm fiche_number           lchg_date lchg_userid  \
0              None         None 2023-08-03 13:29:08      gibs-i
1              None         None 2020-09-25 18:05:31        None
2              None         None 2020-09-25 18:04:02        None
3              None         None 2020-09-25 18:06:16        None
4              None         None 2020-09-25 18:04:02        None
...             ...          ...                 ...         ...
27939          None         None 2024-10-29 22:09:28        basp
27940          None         None 2024-10-31 15:22:28       mccl3
27941          None         None 2024-10-30 15:29:32       sils1
27942          None         None 2024-10-30 15:42:05       sils1
27943          None         None 2024-10-30 20:32:09        basp

      wx_cond_basic faa_dist_office dec_latitude dec_longitude
0              None            None    49.216634   -122.683870
1               VMC            None    29.506111    -95.476669
2               VMC            None    35.533611    -97.641387
3               VMC            None    40.451667   -105.001113
4               VMC            None    38.202220    -77.587501
...             ...             ...          ...           ...
27939          None            None          NaN           NaN
27940           VMC            None          NaN           NaN
27941          None            None          NaN           NaN
27942          None            None          NaN           NaN
27943           VMC            None          NaN           NaN

[27944 rows x 73 columns]

# sequence

In [ ]:
# 连接数据库
conn = pyodbc.connect(conn_str)
# 查询数据
query = """
SELECT     
    [events].*, 
    [aircraft].*, 
    [dt_aircraft].*, 
    [dt_events].*, 
    [dt_Flight_Crew].*, 
    [engines].*, 
    [Events_Sequence].*, 
    [Findings].*, 
    [Flight_Crew].*, 
    [flight_time].*, 
    [injury].*, 
    [narratives].*, 
    [NTSB_Admin].*, 
    [Occurrences].*, 
    [seq_of_events].*, 
FROM [events] 
INNER JOIN [aircraft] ON [events].[ev_id] = [aircraft].[ev_id]
INNER JOIN [aircraft] ON [events].[ev_id] = [aircraft].[ev_id]
INNER JOIN [dt_aircraft] ON [events].[ev_id] = [dt_aircraft].[ev_id]
INNER JOIN [dt_events] ON [events].[ev_id] = [dt_events].[ev_id]
INNER JOIN [dt_Flight_Crew] ON [events].[ev_id] = [dt_Flight_Crew].[ev_id]
INNER JOIN [engines] ON [events].[ev_id] = [engines].[ev_id]
INNER JOIN [Events_Sequence] ON [events].[ev_id] = [Events_Sequence].[ev_id]
INNER JOIN [Findings] ON [events].[ev_id] = [Findings].[ev_id]
INNER JOIN [Flight_Crew] ON [events].[ev_id] = [Flight_Crew].[ev_id]
INNER JOIN [flight_time] ON [events].[ev_id] = [flight_time].[ev_id]
INNER JOIN [injury] ON [events].[ev_id] = [injury].[ev_id]
INNER JOIN [narratives] ON [events].[ev_id] = [narratives].[ev_id]
INNER JOIN [NTSB_Admin] ON [events].[ev_id] = [NTSB_Admin].[ev_id]
INNER JOIN [Occurrences] ON [events].[ev_id] = [Occurrences].[ev_id]
INNER JOIN [seq_of_events] ON [events].[ev_id] = [seq_of_events].[ev_id]
WHERE [events].[ev_id] = '20240910195092'
"""
""

df = pd.read_sql(query, conn)

# 查看结果
print(df.head())

# 关闭连接
conn.close()

df.to_excel('JOIN.xlsx', index=False)

In [ ]:
# 连接数据库
conn = pyodbc.connect(conn_str)

# 编写SQL查询，将所有包含ev_id的表使用INNER JOIN方式连接
query = """
SELECT 
    [events].*, 
    [aircraft].*, 
    [dt_aircraft].*, 
    [dt_events].*, 
    [dt_Flight_Crew].*, 
    [engines].*, 
    [Events_Sequence].*, 
    [Findings].*, 
    [Flight_Crew].*, 
    [flight_time].*, 
    [injury].*, 
    [narratives].*, 
    [NTSB_Admin].*, 
    [Occurrences].*, 
    [seq_of_events].*, 
FROM [events]
INNER JOIN [aircraft] ON [events].ev_id = [aircraft].ev_id
INNER JOIN [dt_aircraft] ON [events].ev_id = [dt_aircraft].ev_id
INNER JOIN [dt_events] ON [events].ev_id = [dt_events].ev_id
INNER JOIN [dt_Flight_Crew] ON [events].ev_id = [dt_Flight_Crew].ev_id
INNER JOIN [engines] ON [events].ev_id = [engines].ev_id
INNER JOIN [Events_Sequence] ON [events].ev_id = [Events_Sequence].ev_id
INNER JOIN [Findings] ON [events].ev_id = [Findings].ev_id
INNER JOIN [Flight_Crew] ON [events].ev_id = [Flight_Crew].ev_id
INNER JOIN [flight_time] ON [events].ev_id = [flight_time].ev_id
INNER JOIN [injury] ON [events].ev_id = [injury].ev_id
INNER JOIN [narratives] ON [events].ev_id = [narratives].ev_id
INNER JOIN [NTSB_Admin] ON [events].ev_id = [NTSB_Admin].ev_id
INNER JOIN [Occurrences] ON [events].ev_id = [Occurrences].ev_id
INNER JOIN [seq_of_events] ON [events].ev_id = [seq_of_events].ev_id
WHERE [events].ev_id = '20240910195092'
"""

# 执行查询并将结果加载到DataFrame
df = pd.read_sql(query, conn)

# 关闭数据库连接
conn.close()

# 查看整合的DataFrame
print(df.head())